### ISSUE TITLE
Support filtering for all test_names

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#103]
Currently DASH data is not added to metadb because the ENUM does not include dash as a supported test.

**Comment by darkk** [comment]
Looks like a bug, alike measurement should be ingested but have `NULL` instead of correct ENUM value.

**Comment by hellais** [comment]
Yes you are right, they are ingested (as I confirm by running: `SELECT * FROM report WHERE report.textname LIKE '%dash%' AND probe_cc = 'US' LIMIT 10;`), however they should have the `test_name` column set otherwise they will not be searchable by the API or easy to filter for.

**Comment by hellais** [comment]
I suspect the same thing is happening with test_name=telegram

**Comment by darkk** [comment]
That should be probably closed as a duplicate of #119 (having more precise description).
