### ISSUE TITLE
Generate daily dumps for ooni-explorer

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#109]
Currently in a fairly ad-hoc way I generated some static dumps for use by ooni-explorer.

We should ideally integrate this into the pipeline so that it is run on a daily basis when measurements are ingested.

In here the code snippet:

```python
import os
import psycopg2
import time
import json

def count_by_country(pgconn):
    results = []
    with pgconn, pgconn.cursor() as c: # main transaction
        c.execute('''SELECT COUNT(measurement.msm_no) as count,
    report.probe_cc AS probe_cc
    FROM measurement
    JOIN report ON report.report_no = measurement.report_no
    GROUP BY report.probe_cc;''')
        for count, probe_cc in c:
            results.append({
                'probe_cc': probe_cc,
                'count': count
            })

    return {
        'results': results
    }

def count_total(pgconn):
    total = -1
    with pgconn, pgconn.cursor() as c: # main transaction
        c.execute('SELECT COUNT(measurement.msm_no) as count FROM measurement')
        row = c.fetchone()
        total = row[0]

    return {
        'total': total
    }

def blockpage_count(pgconn):
    """
    We dump number of blocked sites / total tested per report that contain at
    least 1 blocked site for every country.
    We limit the query to 42, because that is how many charts fit in 3 pages on
    OONI Explorer.
    """
    query = '''
    SELECT block_count,
total_inputs,
test_start_time,
probe_cc FROM (
	SELECT
	SUM(CASE WHEN measurement.confirmed = true THEN 1 ELSE 0 END) as block_count,
	COUNT(input.input) as total_inputs,
	report.test_start_time as test_start_time,
	report.probe_cc AS probe_cc
	FROM measurement
	JOIN report ON report.report_no = measurement.report_no
	JOIN input ON input.input_no = measurement.input_no
	WHERE (report.test_name = 'web_connectivity' OR report.test_name = 'http_requests')
	GROUP BY report.test_start_time, report.probe_cc
)  as block_counts
WHERE block_count > 0
ORDER BY probe_cc, test_start_time ASC
'''
    results_by_country = {}
    with pgconn, pgconn.cursor() as c: # main transaction
        c.execute(query)
        for block_count, total_inputs, test_start_time, probe_cc in c:
            results_by_country[probe_cc] = results_by_country.get(probe_cc, [])
            results_by_country[probe_cc].append({
                'probe_cc': probe_cc,
                'block_count': block_count,
                'test_start_time': test_start_time.strftime('%Y-%m-%dT%H:%M:%SZ'),
                'total_count': total_inputs
            })
    for key, values in results_by_country.items():
        with open('outputs/blockpage-count-%s.json' % key, 'w') as out_file:
            json.dump({
                'results': values[-42:]
            }, out_file)

    return {
        'results': results_by_country
    }

outputs = {
    'count-by-country': count_by_country,
    'count-total': count_total,
    'blockpage-count': blockpage_count
}

def write_output(pgconn, json_path, func):
    with open(json_path, 'w') as out_file:
        print('writing %s' % json_path)
        start_time = time.time()
        obj = func(pgconn)
        print('dump time: %f' % (time.time() - start_time))
        json.dump(obj, out_file)

def main(postgres):
    pgconn = psycopg2.connect(dsn=postgres)
    for key, value in outputs.items():
        json_path = os.path.join('outputs', key + '.json')
        if not os.path.exists(json_path):
            write_output(pgconn, json_path, value)
```
Edit: Updated with the latest version of the script.

**Comment by hellais** [comment]
I needed to make some changes to the `blockpage_count` dump (to keep the file sizes down) and will edit the above comment to reflect the final script.

**Comment by hellais** [comment]
Here are some more dumps that should probably be part of a daily workflow:
```
    query_test_coverage = """
    SELECT COUNT(msmt.msm_no), d.test_name, d.date
    FROM (
	(
		SELECT
		unnest(
		ARRAY[
		'web_connectivity',
		'http_invalid_request_line',
		'tcp_connect',
		'http_header_field_manipulation',
		'meek_fronted_requests_test',
		'whatsapp',
		'vanilla_tor',
		'facebook_messenger',
		'ndt',
		'dash',
		'telegram'
		]) as test_name,
		date_trunc('day', (current_date - offs)) AS date
		FROM generate_series(0, 30, 1) AS offs
	) d
	LEFT OUTER JOIN
	(
		SELECT
		msm_no,
		report.test_name as test_name,
		date_trunc('day', measurement_start_time) as date
		FROM measurement
		JOIN report ON report.report_no = measurement.report_no
                WHERE probe_cc = :probe_cc
		AND measurement_start_time > current_date - interval '30 day'
	) msmt
	ON d.date = msmt.date AND d.test_name::char = msmt.test_name::char
    )
    GROUP BY d.test_name, d.date
    ORDER BY d.date, d.test_name;
    """

    query_network_coverage = """
    SELECT COUNT(DISTINCT probe_asn), d.date
    FROM (
            (
                    SELECT
                    date_trunc('day', (current_date - offs)) AS date
                    FROM generate_series(0, 30, 1) AS offs
            ) d
            LEFT OUTER JOIN
            (
                    SELECT
                    probe_asn,
                    date_trunc('day', measurement_start_time) as date
                    FROM measurement
                    JOIN report ON report.report_no = measurement.report_no
                    WHERE probe_cc = 'IT'
                    AND measurement_start_time > current_date - interval '30 day'
            ) msmt
            ON d.date = msmt.date
    )
    GROUP BY d.date
    ORDER BY d.date;
```

@darkk do you think they should be a materialised view or just a static JSON which is updated by the pipeline?
If it's a materialised view, I think it would give us more flexibility to support more advanced use cases.

**Comment by darkk** [comment]
@hellais I think that "view or json" is a false dichotomy. As we've discussed quite some time ago, all decisions on periodic updates of alike data slices make sense only when the UI part is settled as that representation of data exists only for the purpose to support UI with reasonable latency of the queries, time of generation, and time to update of precomputed data. And, as we've discussed, any solution is good during UI prototyping phase as that is not updated and all those costs are payed just once.

Making a naive materialized view out of those queries has some issues:
- no stats are saved outside of 30d window
- cost of update is 30 times larger than it could be, PostgreSQL (unlike Oracle, for example) does not support partial update of materialized views, but maybe it's something like "30s 30 times larger than 1s"
- the second query alone took 3.5m to execute (YMMV, but you give no other estimates). Maybe that's overestimation, but multiplying that by 232 countries gives ~13 hours of runtime, so, the solution may be a bit suboptimal
- `measurement_start_time` is user-controlled and may produce nonsense in edge cases

Given that issues, **assuming** that we're discussing the steady phase and not the prototyping one, I'd rather suggest to generate some stats per bucket when the bucket is "closed" as the bucket is the unit of the pipeline and further aggregate those stats into something useful for UI.

**Comment by hellais** [comment]
@darkk this is a good point. Based on your comments in here I am thinking that perhaps a good approach could be that of having some fact tables specific for OONI Explorer which get updated when the pipeline ticks with the data from the last bucket.

These fact tables can include some metrics that will then be further aggregated at runtime by querying the OONI Explorer tables.

I have started to experiment with this on the hkgmetadb by creating some `UNLOGGED` tables in the `ooexpl_` namespace (I actually by mistake created one before that was logged and I hope it did not published in the WAL log and replicated).

The jist of the table is the following:

```
CREATE UNLOGGED TABLE ooexpl_recent_msmt_count AS
SELECT
COUNT(msm_no) as msmt_count,
probe_cc,
probe_asn,
test_name,
test_start_time,
bucket_date
FROM measurement
JOIN report ON report.report_no = measurement.report_no
JOIN autoclaved ON autoclaved.autoclaved_no = report.autoclaved_no
WHERE test_start_time > current_date - interval '30 day'
GROUP BY probe_cc, probe_asn, test_name, test_start_time, bucket_date;
```

We can then use this to derive all the stats on the 30 day time window by querying it at runtime and the performance seems pretty OK (example: `SELECT SUM(msmt_count) FROM ooexpl_recent_msmt_count WHERE test_name = 'web_connectivity' AND probe_cc = 'IT'` takes 200ms).

The table size is ~ 35MB + 34MB for indexes.

I will continue this approach for other OONI Explorer related tables for the various sections we need in explorer.

**Comment by darkk** [comment]
Another "cheap" trick that may be useful at some scale for alike data is to "roll" a set of rows those are ALWAYS fetched together. E.g. imagine having a hourly datapoints for some chart but having the minimal fetch granularity of 24 hours (day). In this case single row per day with an array of 24 values may be more performant in some cases due to lower per-row overhead.
But alike tricks need consistent benchmark plan and clear performance goals as every hack may be a premature optimization as well.

**Comment by darkk** [comment]
It's unclear to me if this ticket should be kept open as it currently has no pending actions. I'd suggest to close it and write further needed actions in a follow-up one.

**Comment by hellais** [comment]
This is done.
