### ISSUE TITLE
Add fingerprints for russia

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#115]
Here are some blockpages found in Russia to add to our fingerprint db:

https://explorer.ooni.torproject.org/measurement/20180315T230339Z_AS15378_1OT3ZGTyarLfiET0jYHJZigX2B1oQDdJKdrjkfzq5Zqr30Lvlp?input=http:%2F%2Fqha.com.ua%2F

https://explorer.ooni.torproject.org/measurement/20180315T100250Z_AS6789_KYIQLsidOroJuPSP8DNkM8WFYOwNEAKebucOYOHhr9bwel8Yl3?input=http:%2F%2Fqha.com.ua%2F

The second interestingly shows HTTP status code 451, we should probably have a heuristic that looks for that status code too.

**Comment by hellais** [comment]
A DNS based feature for blocked sites in crimea is the following IP:

```
62.33.207.197
62.33.207.196
```

source measurements: https://explorer.ooni.torproject.org/measurement/20180315T174422Z_AS12688_7Iy8vwd6JYREOl2E6E1PJnNeCVGVKlORQNYhUJ2tKyiWjaEFkY?input=http:%2F%2Fmaidanua.org%2F

**Comment by hellais** [comment]
Another blockpage fingerprint for Russia: https://explorer.ooni.torproject.org/measurement/20180315T160455Z_AS8359_t1zebVigtFmS7kxCOCe3P77uClvciZHmKIwutI13x3Wcpe5t9V?input=http:%2F%2Futronews.org

**Comment by anadahz** [comment]
Another one:
https://explorer.ooni.io/measurement/20181229T072204Z_AS39289_xlYTdPez910QvwBFCYyD3sgv0hQq1WBgbhW3lMjIs3MVMUdGtg?input=http:%2F%2Fblackberry.com

tag:`http://89.185.75.227/451/`

**Comment by hellais** [comment]
Added these in: https://github.com/ooni/pipeline/pull/289
