### ISSUE TITLE
Fasle negative report - TR fingerprint

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#117]
I guess this report should be tagged with DNS blocking:
https://explorer.ooni.io/measurement/20180403T183403Z_AS9121_FfHjDmPkC0E5UoU3JMZoXJ2KRrMVyqdeTkHchmGEqAonEU64u4?input=http:%2F%2Fbeeg.com

```
dns_consistency: "inconsistent" 
title_match: false
headers_match: false
```

**Comment by hellais** [comment]
Added this fingerprint to: https://github.com/ooni/pipeline/pull/289
