### ISSUE TITLE
Add fingerprints for Ukraine

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#121]
Here is a blockpage served on a private IP in Ukraine: https://explorer.ooni.io/measurement/20180615T125414Z_AS35362_GaNRQSk6HlZ1Aa2ZD9UoGiIgu3KcLMM5M5yk5dEswhEkIprbnA?input=http:%2F%2Fvk.com%2Fminitrue

**Comment by anadahz** [comment]
Another fingerprint of a block page in Ukraine:
`Location: "http://blocked.triolan.com.ua?refer="`

Example measurement:
https://explorer.ooni.io/measurement/20190228T101440Z_AS13188_LUWIsztkSQlApx6cliGdGzztCM6Hs2MFI3ybFEYuaIG5W8cQS6?input=http:%2F%2Freporter-crimea.ru

**Comment by hellais** [comment]
Added these to: https://github.com/ooni/pipeline/pull/289
