### ISSUE TITLE
Add fingerprints for Kyrgyzstan

### ISSUE THREAD

**Issue by agrabeli** [ooni/pipeline#122]
Here is a block page served in KG: https://explorer.ooni.torproject.org/measurement/20180126T000430Z_AS8449_pk15Mr2LgOhNOk9NfI2EarhUAM64DZ3R85nh4Z3q2m56hflUGh?input=http:%2F%2Farchive.org

**Comment by hellais** [comment]
Added this to: https://github.com/ooni/pipeline/pull/289
