### ISSUE TITLE
Add sync-test-lists script to pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#123]
We should have a part of the airflow pipeline a stage that synchronises the test lists from the citizenlab/test-lists repo.

This script is currently part of ooni/orchestra and some improvements have been made in this branch: https://github.com/ooni/orchestra/pull/50.

This allows the orchestrate API `urls` endpoint to work, ex: https://orchestrate.ooni.io/api/v1/urls?country_code=IT & https://events.proteus.test.ooni.io/api/v1/urls.

Ideally this would be rolled out before we make a beta of the revamped probe-ios and probe-android apps.

**Comment by darkk** [comment]
That's rolled out as https://github.com/ooni/sysadmin/commit/54cf5b7381cf8788cdcd9a349a43fcd550ab05e1 in PR https://github.com/ooni/sysadmin/pull/234
I believe, it's okay to maintain `sync-test-lists` in `ooni/orchestra` tree and I see no strong reason to move it here till the moment when we'll need category codes in the metadata DB (e.g. to build "auto-generated report" or respond with that data in API).
So I'm closing it for the moment.
