### ISSUE TITLE
Fasle positive report - Telegram

### ISSUE THREAD

**Issue by Sea-n** [ooni/pipeline#125]
It will report **Web version of Telegram** as blocked
![screenshot_20181101-220253](https://user-images.githubusercontent.com/10102616/47856406-1b1deb00-de22-11e8-9d2f-0e404da15f42.png)

I think it's caused by [404 Not Found](http://149.154.175.50/) and [501 Not Implemented](http://149.154.167.51/) in API, which should not use **HTTP GET** to test
![screenshot_20181101-220339](https://user-images.githubusercontent.com/10102616/47856408-1b1deb00-de22-11e8-8790-20960224fe0c.png)

```json
{
  "telegram_http_blocking": false,
  "telegram_tcp_blocking": false,
  "telegram_web_failure": null,
  "telegram_web_status": "blocked"
}
```
![screenshot_20181101-220302](https://user-images.githubusercontent.com/10102616/47856407-1b1deb00-de22-11e8-881a-f08d2c729b13.png)

**Comment by darkk** [comment]
Yes, looks like false positive to me.

Telegram Web (and telegram app) are actually working for you , right?

Thanks for `id`, it'll help to reference the measurement when it'll be ingested (at midnight).

**Comment by Sea-n** [comment]
@darkk Yeah, my country (Taiwan) should have no limit to Telegram
