### ISSUE TITLE
Document how to partially reprocess measurements

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#135]
There are times in which we may make some changes to the centrifugation stage and we may want to reprocess a subset of the measurements.

It's useful to document how to do this and update the `Reamde.md` to reflect.

These docs should also include reference to how a "fast path" for some measurements can be achieved.

**Comment by darkk** [comment]
[Report deletion](https://github.com/ooni/pipeline/blob/master/docs/delete-report.md) is also relevant to this ticket and is documented in the linked note.

**Comment by gabelula** [comment]
@darkk Are you working on this one? We need more documentation on this issue.

**Comment by hellais** [comment]
This is documented inside of https://github.com/ooni/pipeline/pull/183 and those docs are really useful!

Thanks for putting them together.
