### ISSUE TITLE
Update the confirmed and anomaly columns as part of centrifugation

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#146]
As discussed in: https://github.com/ooni/api/issues/59#issuecomment-475587287

It seems like the `confirmed` and `anomaly` tables are not currently being updated.

I think that for the sake of coming up with an MVP that implements the heuristics present in the current explorer we define:

`confirmed` we saw a blockpage of the country of the measurement for web_connectivity measurements (we don't mark as confirmed any other measurement types for the moment)
`anomaly` in the case of web_connectivity the value of `blocking != 'false' AND blocking != NULL` OR it's confirmed

@darkk how would you suggest we handle updating the values of these columns as part of the centrifugation stage?

My proposal is to do the following:

* [ ] Re-run as a one-off a query similar to that we do for the ooexpl_website_msmts MAT VIEW (see: https://github.com/ooni/pipeline/pull/144/files#diff-15300963e74e04b5836ccfc9f0b1f6abR52)
* [ ] Add to the centrifugation stage logic to update this columns once a certain bucket is being `ingest`ed, `reingest`ed or `reprocess`ed

Does this seem reasonable to you?

**Comment by darkk** [comment]
I believe that's done by 5fac5cf96b4c7416f5ab2c4b41f709d3bca0a9b6 at #144, so I'm closing the ticket.
