### ISSUE TITLE
Document CODE_VER_REPROCESS in centrifugation.py

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#150]
In the centrifugation.py script there is a variable called CODE_VER_REPROCESS.

From chatting with @darkk we agreed that it should be better explained and if it's not in fact   CODE_VER_REINGESTION.

**Comment by hellais** [comment]
@darkk can you clarify the difference between these two flags?

There is no mention of these flags in the reprocessing doc.

**Comment by darkk** [comment]
@hellais can you clarify, what flags do you mean?
There is no such thing as `CODE_VER_REINGESTION`.
As far as I understand `CODE_VER_REPROCESS` is described accurately.

**Comment by hellais** [comment]
I think this was something that came up when we were chatting about this in person. I recall that when I showed the line of code with `CODE_VER_REPROCESS` in it (see: https://github.com/ooni/pipeline/blob/master/af/shovel/centrifugation.py#L43) you were unsure of the purpose and were wondering if the meaning of this flag was in fact to trigger REPROCESSING of measurements or if i was meant to trigger REINGESTION.

Do you remember this discussion?

I guess the question here is if you could clearly state the purpose of this flag in the code and when and if somebody should be changing it or what is the meaning of having it in the code.

**Comment by darkk** [comment]
Yep, I remember that discussion.
I re-read relevant code and, seems, it does not trigger reingestion and everything is named correctly.
The purpose is to have a constant defined as "the oldest possible `CODE_VER` value".
As far as I see, setting the `autoclaved.core_ver` to `0` has no special meaning (unless I'm mistaken).
Maybe, [`UPDATE autoclaved SET code_ver = 1`](https://github.com/ooni/pipeline/blob/master/tests/test_integration.py#L182) should rather be replaced with `code_ver = 0` to put those two magic values in sync. There should be no difference as `min(min_compat_code_ver)` is `2`.

**Comment by hellais** [comment]
Excellent, thanks for clarifying that. I think we can consider this issue resolved then.
