### ISSUE TITLE
Add blockpage fingerprint for CO

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#156]
Blockpage fingerprint for Colombia:

```
<p align="center"><b><font size="4" face="Book Antiqua">Esta página ha sido bloqueada por disposición del Ministerio de las TIC,</font></b></p>
```

Example measurement:
https://explorer.ooni.torproject.org/measurement/20190114T112310Z_AS262928_N3ChIPo5QSMMZ3qgA25G9QHE55suubZbPPkAfmNLkmOXuh9ZXJ?input=http:%2F%2Fwww.eurogrand.com%2F

**Comment by hellais** [comment]
Added this to: https://github.com/ooni/pipeline/pull/289/files
