### ISSUE TITLE
Add blockpage fingerprint for ES

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#157]
Not sure if this is a country-wide block, though the headers are showing the presence of Huawei equipment `V2R2C00-IAE/1.0` as in the [Cuban blog post](https://ooni.torproject.org/post/cuba-internet-censorship-2017/#huawei-equipment-in-cuba).

Example measurement:
https://explorer.ooni.torproject.org/measurement/20180523T140922Z_AS12430_ZRebsyxxswrlcQhz1wEs6apHw5Br7FWNc1LenCsVR6Rkl1OCSD?input=http:%2F%2Fwww.marijuana.com

**Comment by hellais** [comment]
Added to: https://github.com/ooni/pipeline/pull/289
