### ISSUE TITLE
Add blockpage fingerprints for IT

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#158]
Quite similar to #157 , though here the following header reveals the presence of the [IPCop](http://ipcop.sourceforge.net/) firewall software (if we can trust HTTP headers found on measurements):
` X-Cache: "MISS from ipcop.itas" `

Example measurement:
https://explorer.ooni.torproject.org/measurement/20170216T161517Z_AS203469_NhQfyO3SkGoX5gdyzo1VRQTrZv1HcQgzudlItMI4YxuSUfgLib?input=http:%2F%2Fwww.pokerstars.net

**Comment by anadahz** [comment]
Another one:
https://explorer.ooni.io/measurement/3N5bdjWAdVjZubaIyAxCCAg0HiZYWfT1YLgz6cI0zRq1XTjHzBmGg49AbRxOGILi?input=http:%2F%2Fwarc.jalb.de

tag: `WebProxy/1.0 Pre-Alpha`

**Comment by hellais** [comment]
done: https://github.com/ooni/pipeline/pull/289
