### ISSUE TITLE
Add blockpage fingerprint for MX

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#159]
A blockpage fingerprint detected in Mexico.
Perhaps similar infrastructure with #157 and #158 .

Example measurement:
https://explorer.ooni.torproject.org/measurement/20190306T161639Z_AS22908_1iCBIVT3AGu4mDvEtpl0ECfxp1oSw8UYXSg82JFQ1gOIqOvw8y?input=http:%2F%2Fwww.pornhub.com%2F

**Comment by hellais** [comment]
Added in #289
