### ISSUE TITLE
Add blockpage fingerprint for PK

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#160]
A blockpage fingerprint detected in Pakistan.
Perhaps similar infrastructure with #157 , #158 and #159 .

Example measurement:
https://explorer.ooni.torproject.org/measurement/20180721T184612Z_AS45773_w5kQp1GbCQUbIv3VDzezjxNx1nCt3IaW7WpvrZTNvayksz9FBK?input=http:%2F%2Fwww.xbox.com

**Comment by hellais** [comment]
Added in #289
