### ISSUE TITLE
Add blockpage and middlebox fingerprints for AE

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#163]
Somebody forgot to change the default template.
Possible blockpage fingerprint for AE.

Example measurement:
https://explorer.ooni.io/measurement/20170423T142350Z_AS0_5EG4lO5Z8KHN2jwbqB5hQqxlC44iXq2A2YCxoASGvY5Z05KrGL?input=http:%2F%2Fwww.foxnews.com

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20170509T041918Z_AS5384_fSeP50M6LS3lUhIarj2WhbQNIQS8mKtvhuxEhwJOhgheEL7EsZ?input=http:%2F%2Fanonym.to

tag:  [SG4000](https://online.antlabs.com/downloads/SG%204%20Product%20Data%20Sheet%20-%20r1_6.pdf)

**Comment by hellais** [comment]
Added in #289
