### ISSUE TITLE
Add captive portal blockage fingerprints for AT

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#167]
Captive portal blockage fingerprints for Austria triggered by the `Barracuda/NGFirewall` middleboxes.

Example measurements:
https://explorer.ooni.io/measurement/20170814T120242Z_AS8447_g6CoCriPHXMWjXJHwZ9kjJmTusVWVPYEsOKOOhF1HLwrHR29hp?input=http:%2F%2Fwww.aleph.to

https://explorer.ooni.io/measurement/20180215T142531Z_AS31543_HutYcy6eALgop44KgGsXAsaF2i7v4feM6DP5vb2hST8nZdmWta?input=http:%2F%2Fanonymizer.secuser.com

**Comment by hellais** [comment]
Thanks! Added to #289
