### ISSUE TITLE
Add blockpage fingerprint for BE

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#168]
Fingerprint blockpage for Belgium.

Example measurement:
https://explorer.ooni.io/measurement/20171106T080745Z_AS5432_m0LkLhXH3oxwworJZUpHGmPeJV2Abk3TMxr2dz8wu04ziIUAGA?input=http:%2F%2Fguardster.com%2F

tag:`Barracuda (Web Filter)`

**Comment by hellais** [comment]
Added in #289
