### ISSUE TITLE
Add blockpage fingerprints for CA

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#169]
Add blockpage fingerprint for Canada.

Example measurement:
https://explorer.ooni.io/measurement/20180724T151542Z_AS577_YiqZVd01jKCgmtm4Ixf6z2uzSBcFSsXkeN6NIDjHl1dtWZ6VrX?input=http:%2F%2Fwww.genderandaids.org

tag:`Barracuda/NGFirewall`

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20171026T125929Z_AS0_nkYRKqxCJy1PZQ9yBcsFuG61hFzZRYeio3N21CEBwot7MiikfZ?input=http:%2F%2Fwww.schwarzreport.org

tag: `Cisco-WSA/8.8.0-085`

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20181010T185819Z_AS5664_EeT6QJ84dSl7QaHu9Dwb5TcByIY2qiGrdtcyZlSFotmQlc53Hg?input=http:%2F%2Fwww.sportingbet.com

tag: `Cisco-WSA/8.5.4-038`

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20170604T114135Z_AS852_pZtNoyGV6fO5K97OJwwhM3ShmlWnuxKHLGrWbjSi4omt9KvyIi?input=http:%2F%2Fwww.xroxy.com

tag: `Cisco-WSA/10.1.1-230`

**Comment by hellais** [comment]
Added in #289
