### ISSUE TITLE
Add blockpage fingerprint for PA

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#170]
A blockpage fingerprint detected in Panama.

Example measurement:
https://explorer.ooni.io/measurement/20170302T184253Z_AS11556_LrU69C7D1dqVTi05dMN0jPphf601DuAzMnFBrehfFvR4ccwfoe?input=http:%2F%2Flifestream.aol.com

tag: `BarracudaHTTP 4.0`

**Comment by hellais** [comment]
Added in #289
