### ISSUE TITLE
Add blockpage fingerprints for US

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#171]
Blockpage fingerprints detected in USA.

Example measurements:
https://explorer.ooni.io/measurement/20171029T080350Z_AS209_xtJYWXrUShSnXnvStZUPWsVpqVhT0hOzR749tbJgzxF9OkR1Bn?input=http:%2F%2Fwww.vanguardnewsnetwork.com

https://explorer.ooni.io/measurement/20180123T210247Z_AS7385_VLsJ9z4UYNZIMUK3Nc4cyaXctKPnnIsxIhuU97X4XWvSAubgZs?input=http:%2F%2Fwww.figleaves.com

tags: `Barracuda/NGFirewall`, `BarracudaHTTP 4.0`

**Comment by anadahz** [comment]
A fingerprint for Websense's Forcepoint equipment blockpage.

Example measurement:
https://explorer.ooni.io/measurement/20180406T152727Z_AS39942_lquPnt0vjeXydfleOdSkxyjst6VTiUWb58f3x5qlFKTSlTIQLG?input=http:%2F%2Fflirtylingerie.com%2F

tag: `Forcepoint`

**Comment by anadahz** [comment]
A fingerprint for a variant of netsweeper's equipment blockpage.

Example measurement:
https://explorer.ooni.io/measurement/20171129T155619Z_AS11714_vJUMktHjy0cQGKqYqY3fgOQQLVNfnxb1V11fvP6jTXTbbTX60e?input=http:%2F%2Fwww.pandora.com

tag: `netsweeper`

**Comment by anadahz** [comment]
Another one.

Example measurements:
https://explorer.ooni.io/measurement/20170504T143706Z_AS16657_2LnvAcQgpCrjBG46Fb5EKr50PIL40W0ppwNcXp9WCCatbPboXK?input=http:%2F%2Fchinadaily.com.cn

https://explorer.ooni.io/measurement/20170411T170124Z_AS46491_ntYaNL2kdnuHFhOpkSgje3aadGsvRW8oadtjIC71DuiX06z4yy?input=http:%2F%2Fwww.exgay.com

https://explorer.ooni.io/measurement/20170915T220312Z_AS22935_6FKfune3ZuFavfORPXNul209Ffwv3jL7RyjzMJppxYju2caAoE?input=http:%2F%2Fwww.breastenlargementmagazine.com

tag: `iboss`

**Comment by anadahz** [comment]
Another one and possibly a false negative.

https://explorer.ooni.io/measurement/20180914T010619Z_AS11427_d3lligD9zAEneBLYeI8Mt2JUpVBC2y5zFZ1EG3XNLo1smBQa48?input=http:%2F%2Fmoqavemat.ir

tags: `IG3000`, `false negative`

**Comment by anadahz** [comment]
Another one:

https://explorer.ooni.torproject.org/measurement/20170628T182856Z_AS25605_Lev8VClbbZplNkYfBGujzPiKFI7rHxERx9SNwOfuR1M8WCTBSZ?input=http:%2F%2Fwww.aceshigh.com

tag: `alert.scansafe.net`

**Comment by anadahz** [comment]
https://explorer.ooni.io/measurement/20170722T013346Z_AS14340_QXOwhyfxJUPRGWsCqanoOycTnbHcpU4CW3NBNXUMMbxbi3Q6I3?input=http:%2F%2Fwww.blubster.com

tag: `http://184.168.221.96:6080/php/urlblock.php`

**Comment by anadahz** [comment]
https://explorer.ooni.io/measurement/20181118T123404Z_AS7922_pgeD0Ka5ySsyl55RBYXO07V82WoH0uggCYFJsvlcp2d55Tju3i?input=http:%2F%2Fwww.acdi-cida.gc.ca

tags: `https://gateway.wifast.com:443/wifidog/login/?gw_address`, `Hughes Technologies Embedded Server`

**Comment by anadahz** [comment]
https://explorer.ooni.io/measurement/20190205T191943Z_AS26638_QbFGhgqZ8sqXmCQrZNrNgB0RWB6EUfjFYPbKYOgaihiWLv5xNb?input=http:%2F%2Ftwitter.com%2F

tag: `https://mpswebfilterwashbu.mpls.k12.mn.us:6082/php/uid.php?vsys=1&rule=1&url=http://twitter.com%2f`

**Comment by hellais** [comment]
These have been added to #289
