### ISSUE TITLE
Add blockpage fingerprint for VI

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#172]
Blockpage fingerprint detected in Virgin Islands.

Example measurement:
https://explorer.ooni.io/measurement/20171203T130750Z_AS14434_iviy15O0b7YXVRoTMaqS4O0w1w9NfVaOL4l3KoV4Y9mJEq33X0?input=http:%2F%2Fcompany.wizards.com%2F

tags: `BarracudaHTTP 4.0`, `false negative`

**Comment by hellais** [comment]
Added in #289
