### ISSUE TITLE
Add blockpage fingerprint for KW

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#174]
A blockpage fingerprint for Kuwait.

Example measurement:
https://explorer.ooni.io/measurement/20170804T144746Z_AS42961_nClauBGJlQ5BgV1lAVD72Gw8omqphSogfCSLAc55zTAdlcpzTA?input=http:%2F%2Fwww.radioislam.org

**Comment by hellais** [comment]
Thanks! Added to #289
