### ISSUE TITLE
Add blockpage and middlebox fingerprints for AR

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#178]
A blockpage and middlebox fingerprints for Argentina.

Example measurement:
https://explorer.ooni.io/measurement/20170312T225529Z_AS0_hV7ESTIV4phKrhXxhO9NTxc5XrcXsgzPqZzEkYbrSjgPv9Xyor?input=http:%2F%2Fwww.erogeschichten.com

tag: `Cisco-WSA/10.1.0-204`

**Comment by hellais** [comment]
Thanks! Added to #289
