### ISSUE TITLE
Add blockpage and middlebox fingerprints for AU

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#179]
A blockpage and middlebox fingerprints for Australia (similar to #178 ).

Example measurement:
https://explorer.ooni.io/measurement/20171106T070150Z_AS9426_z1R8gTMEhKzX69ZVymQrubL1f5FliuHXuFy6Z7TRomXpC5w1jr?input=http:%2F%2Fwww.rollitup.org

tag: `Cisco-WSA/10.1.1-235`

**Comment by anadahz** [comment]
Another blockpage fingerprint and a false negative match.

Example measurement:
https://explorer.ooni.io/measurement/20180125T012951Z_AS0_gyX2DUR5Q1W5V7gAlvUwnnEAH5tbEkEexlUu5qO8ZphH2uEjk6?input=http:%2F%2F8thstreetlatinas.com

tags: `false negative`, `ZZ`, `www.webscanningservice.com`

**Comment by anadahz** [comment]
Another one:
https://explorer.ooni.io/measurement/20171119T095401Z_AS1221_sSYzvupLp9kaEiQiBBS4nlqpHzsO59Eh5SIyp60Z83ah5uRXtM?input=http:%2F%2Fwww.twistedinternet.com

tag: `go.telstra.com.au/broadbandprotect/networkprotectionstandard?originalURL`

**Comment by hellais** [comment]
Thanks! Added to #289
