### ISSUE TITLE
Add middlebox fingerprints for BR

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#180]
Middlebox fingerprint for Brasil.

Example measurement:
https://explorer.ooni.io/measurement/20171206T160707Z_AS10429_4pfvLyNqYHpbLQI9tIpuQr7CPgvOOGaZbbnm7gMIZKdBE4oXJ9?input=http:%2F%2Fcrackspider.net

tags: `Cisco-WSA/9.1.2-010`,`false negative`

**Comment by anadahz** [comment]
Another one.

Example measurement:
https://explorer.ooni.io/measurement/20181023T171547Z_AS262318_cr2e8wzvNXORo80y7pOT9iqxLDOaHAboXakfU8qnQkWh50K0cs?input=http:%2F%2Fwww.pandora.com

tag: `Sonicwall`

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20180220T211731Z_AS53088_hBULQ0NRrcPjUkuf1s4aauypxFZvLqfnVvb0kGVzp7QZ9pJYYD?input=http:%2F%2Fwww.pornhub.com%2F

tag: `GoAhead-Webs/2.5.0`

**Comment by hellais** [comment]
Thanks added them to #289.

The last one:
> https://github.com/ooni/pipeline/issues/180#issuecomment-489452449

Is not actually a blockpage, but is the weird redirect behaviour of pornhub.com
