### ISSUE TITLE
Add blockpage and middlebox fingerprints for DE

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#181]
Blockpage and middlebox fingerprints for Germany.

Example measurements:
https://explorer.ooni.io/measurement/20180312T143953Z_AS3320_Kumlzdy0NSKyLoB0bt9PHKXp4OKItFMuYqMCw4ouQJapQFVUNR?input=http:%2F%2Fwww.hackhull.com

https://explorer.ooni.io/measurement/20170506T130315Z_AS47610_cpNzdaQAx60UxJxEdXh54qBxxEKLexnoPdNam8KDJ181yCbZir?input=http:%2F%2Fspys.ru

tag: `Cisco-WSA/5.0.0`, `Cisco-WSA/10.1.1-230`

**Comment by anadahz** [comment]
Another one.

Example measurement:
https://explorer.ooni.io/measurement/20190113T190405Z_AS60068_P7XDllvakD4djyFssTl9xVyVJI5bxSVl6mCxsGFsPLd94ohP8U?input=http:%2F%2Foccupystreams.org

tag: `blocked.netalerts.io`

**Comment by hellais** [comment]
Thanks! Added to #289
