### ISSUE TITLE
 Add blockpage and middlebox fingerprints for DK

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#182]
Blockpage and middlebox fingerprints for Denmark.

Example measurements:
https://explorer.ooni.io/measurement/20171121T193103Z_AS41746_lcM0SY6VKKQ9SnL3SUrh6aiH2hgJUkCs1zGtWuEjYTgVHqW7Lz?input=http:%2F%2Fwww.wetplace.com

tag: `Cisco-WSA/9.1.1-074`

**Comment by hellais** [comment]
Thanks! Added to #289
