### ISSUE TITLE
Add blockpage and middlebox fingerprints for FR

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#184]
Blockpage and middlebox fingerprints for France.

Example measurements:
https://explorer.ooni.io/measurement/20170213T143932Z_AS57584_U1gMCvIFLNWIKnSrpWTLrN9oewaHiT0DdKjLaT3MiMqnBk3J3U?input=http:%2F%2Fwww.23.org

tag: `Cisco-WSA/9.1.1-074`

**Comment by anadahz** [comment]
https://explorer.ooni.io/measurement/20170213T102635Z_AS15557_9Z8MxApbDh5RtXUqLL16sYyY5tXWlvYkqSa7YVmSlCTn8KKjP8?input=http:%2F%2Fpornhub.com

tags: `/cgi-bin/welcome.cgi\"></HEAD><BODY></BODY></HTML>`, `Embedded HTTP Server`

**Comment by anadahz** [comment]
https://explorer.ooni.io/measurement/20170404T230752Z_AS5511_PuuUMPTRZ3UawVdvAkFnnaMFzLJ9eMspdsrN6qs2ZVJBKlzKwD?input=http:%2F%2Fwww.pornhub.com%2F

tags: `HTTP Server 1.0`, `Huawei Eudemon1000E-X3`

(Could be this middlebox: https://support.huawei.com/enterprise/en/security/eudemon1000e-x3-pid-8577681/software)

**Comment by FedericoCeratto** [comment]
Huawei Eudemon1000E-X3 sets an interesting cookie:
"SESSIONID=IgAAAFIgu6YUVZGubWCrElQOqSzUcic97PhDorW6XEY=&IgAAAFIgu6YUVZGubWCrEg==&Huawei Eudemon1000E-X3&langfrombrows=&copyright=2010-2013"

**Comment by anadahz** [comment]
> Huawei Eudemon1000E-X3 sets an interesting cookie:
"SESSIONID=IgAAAFIgu6YUVZGubWCrElQOqSzUcic97PhDorW6XEY=&IgAAAFIgu6YUVZGubWCrEg==&Huawei Eudemon1000E-X3&langfrombrows=&copyright=2010-2013"

@FedericoCeratto I may miss something what is interesting with this cookie?

**Comment by hellais** [comment]
Thanks! Added to #289
