### ISSUE TITLE
Add blockpage and middlebox fingerprints for VN

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#186]
Blockpage and middlebox fingerprints for Vietnam.

Example measurement:
https://explorer.ooni.io/measurement/20130506T043500Z_IBzthJbAAPsdFZQLPrjMbAwlELzGqtabqMatKpBqqBSWnUyQnA?input=http:%2F%2Fwww.sos-reporters.net

tag: `InnGate300`

**Comment by hellais** [comment]
Thanks! Added to #289
