### ISSUE TITLE
Add blockpage fingerprint for GR

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#187]
A blockpage fingerprint for Greece.

Example measurement:
https://explorer.ooni.io/measurement/20140703T083044Z_xCnGLSGTjBtyHfCTRvswNcQAjkhIwkpDWJrXqyTCjeMVCECmnv?input=http:%2F%2Fwww.royalvegascasino.com%2F

tags: `WebProxy/6.0`, `false negative`, `ZZ`

**Comment by hellais** [comment]
Thanks! Added to #289.
