### ISSUE TITLE
Add blockpage fingerprints for GB

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#188]
A blockpage fingerprint for Great Britain.

Example measurement:
https://explorer.ooni.io/measurement/20170209T201940Z_AS12576_ycIIuNLw50QemJrxTPWl2vDfkPKjnZktbSY2hI6pU5x0AG8urA?input=http:%2F%2Fwww.asianangels.com

tags: `WebProxy/5.2`, `false negative`

**Comment by anadahz** [comment]
Another blockpage fingerprint.

Example measurement:
https://explorer.ooni.io/measurement/20160401T061018Z_ehdZlDMzbUsYhYSGSWalmqKnqGIynfVHQhKvocrcKEmFeynXHd?input=Trans500.com

tags: `block.nb.sky.com`

**Comment by anadahz** [comment]
Another one.

Example measurement:
https://explorer.ooni.torproject.org/measurement/20181118T215552Z_AS12576_LXCqBnsH90yHeMcE6LNDYwOl6IHnop0dTroWxA5NE7AhJ8vFn9?input=http:%2F%2Fwww.globalfire.tv

tag: `http://myaccount.ee.co.uk/anonymous-content-lock/`

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20181120T092944Z_AS199335_6V7Di7t3qUP7qVBYDlOHo9nxgle5NMQIDGHV50wtmCLuZTVPzU?input=http:%2F%2Fwww.microsofttranslator.com

tag: `Lightspeed Content Filter { 40Gb Edition }`

**Comment by anadahz** [comment]
Another blockpage:
https://explorer.ooni.io/measurement/20170605T124503Z_AS0_eVo3z6wXAYDVrAZDsgqiM7pPlLuKR7l4zNF8oEUrGmZ62HWU4l?input=http:%2F%2Frockettube.com

tags: `https://account.nowtv.com/broadband-buddy/blocked-pages/`, `geoip`

**Comment by anadahz** [comment]
Another one:
https://explorer.ooni.io/measurement/20180127T090022Z_AS5378_NK5M8lt6WbL1LOdiIooPX5PXla2DQDlAkGIK4HimIWbUpoMlj8?input=http:%2F%2Fwww.imageshack.us

tag: `www.vodafone.co.uk/contentcontrolpage/vfb-category-blocklist.html`

**Comment by anadahz** [comment]
Another one:
https://explorer.ooni.io/measurement/20190203T142614Z_AS60339_PIMtdDSw9QEc2C9hDgA8tx5LZDrdmUP8ZFsSkdGRX2QNnisqaM?input=http:%2F%2Fwww.peacefire.org%2Fcircumventor%2Fsimple-circumventor-instructions.html

tag: `http://three.co.uk/mobilebroadband_restricted`

**Comment by anadahz** [comment]
https://explorer.ooni.io/measurement/20170404T062436Z_AS60339_QJa9jOkZrduHeY2fH5oQmChKFtqwM1RzB3RG2AAjE1IMDMXp59?input=http:%2F%2Fwww.naughty.com

tag: `WebLogic`

**Comment by hellais** [comment]
Added to #289
