### ISSUE TITLE
Add blockpage fingerprint for ID

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#190]
A blockpage and middlebox fingerprint for Indonesia.

Example measurement:
https://explorer.ooni.io/measurement/20170826T071505Z_AS24526_40Tlz7tR7m0UVaTRZi5EUtsuAjHnYuAgDlNjkec64t70Tujbo9?input=http:%2F%2Fwww.budweiser.com

tags: `Netcache`

**Comment by hellais** [comment]
Thanks!

Added to #289
