### ISSUE TITLE
Add blockpage fingerprint for CH

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#191]
A blockpage fingerprint for Switzerland.

Example measurement:
https://explorer.ooni.io/measurement/43xnHPgN3gi0kt6EhmF2VbIOfQSV5CN9TXicU0A5ChlYejSGjT24Y1noM2DJgdk8?input=http:%2F%2Fwww.wetplace.com

tag: `Squidguard`

**Comment by hellais** [comment]
Thanks!

Added to #289
