### ISSUE TITLE
Add blockpage fingerprint for EG

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#193]
A blockpage fingerprint for Egypt.

Example measurement:
https://explorer.ooni.io/measurement/20171126T053414Z_AS36992_8F2afEp0cM9V7Who1mEJUpqX2fGVbvgoZ2DfVGi3Nv3lQzypzV?input=http:%2F%2Fkh-press.com

tags: `notification.etisalat.com.eg`

**Comment by hellais** [comment]
Added to #289. Thanks!
