### ISSUE TITLE
Add blockpage fingerprint for PH

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#194]
A blockpage fingerprint for Philippines.

Example measurement:
https://explorer.ooni.io/measurement/20180114T101054Z_AS0_SptN5g552QQ9wpfhEBsOTeuOkrpYOQgCBc4JQXNy9GFGxarbEf?input=http:%2F%2Fhightimes.com

tags: `surfalert.globe.com.ph`, `ZZ`

**Comment by anadahz** [comment]
A blockpage/paywall:
https://explorer.ooni.io/measurement/20171014T140144Z_AS10139_gQG3LIHnMZH3IsSJuPmMlLM8qDj3kKfHxJJGyPblDQ1AOFFyBX?input=http:%2F%2Fwww.bittorrent.com

tag: `http://cube.sunbroadband.ph:8020/balanceToOffer/init`

**Comment by hellais** [comment]
I should note that the second look actually like a captive portal-ish type site saying: 
> You are about to access a site that is not part of your existing data package. To resume internet browsing, you may subscribe to any of our data offers below

Thanks! Added to #289
