### ISSUE TITLE
Add blockpage fingerprint for SG

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#195]
A blockpage fingerprint for Senegal.

Example measurement:
https://explorer.ooni.io/measurement/20170905T231542Z_AS9874_3TJ6zyJeL17MVkTArLLsVfDxuMEPzfWB2rm4UbxiDuwtSiuNf3?input=http:%2F%2Fwww.playboy.com

tag: `http://www.starhub.com:80/personal/broadband/value-added-services/safesurf/mda-blocked.html`

**Comment by hellais** [comment]
Thanks! Added to #289
