### ISSUE TITLE
Add blockpage fingerprint for CL

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#196]
Add a blockpage fingerprint for Chile.

Example measurement:
https://explorer.ooni.io/measurement/20170413T224353Z_AS0_Izup11aUZt39zCD1TSFUC1uvOmg7tO1bhwRHWEYsk2WgNrgObZ?input=http:%2F%2Fshareaza.com%2F

tag: `Kerio Control Embedded Web Server`, `geoip`

**Comment by hellais** [comment]
Thanks! Added to #289
