### ISSUE TITLE
Reduce the latency of publication of uploaded measurement to less than daily

### ISSUE THREAD

**Issue by darkk** [ooni/pipeline#199]
To reduce publication period from current 24h to something like 15m following _may_ be done:

- update collector to rename reports to outgoing spool more often than once per 24h (the original reason for separation of "ready" and "outgoing" spools may also be questioned)
- re-archive the freshest `canned` file in the current bucket as new reports come in (extending the freshest file if needed, updating `index.json.gz`)
- make `autoclaved` files **appendable** during _autoclaving_ step
- make `meta_pg` dependent on `autoclaved_tarlz4_s3_sync` to prevent race
- postpone `reports-tgz` creation, `canned` S3 upload and [cleanups in the DAG](https://github.com/ooni/pipeline/blob/master/docs/airflow-pipeline.png) till the bucket is "closed"
- ensure that two Dag instances are not running concurrently on top of the same bucket (Airflow does not guarantee that)
- ensure that _centrifugation_ step has reasonable performance (think of issues like #140 that may make `meta_pg` taking unreasonable amount of time)

All of that is relatively simple, besides, maybe _appendable_ tar files, so I'd expand on that a bit.

The goal is to preserve _existing_ and _relevant_ binary bits of autoclaved files in S3 to prevent races between S3 uploads and MetaDB updates. The _possible_ way is to append new reports to existing tar.lz4 autoclaved files. To make appending to tar archive possible it's needed to have ability to strip tar file trailer (two zero blocks) for a compressed file without changing other bits of the file. That's possible if the last LZ4 frame of the tar.lz4 file has no measurement data. Currently, it _usually_ has last measurement, `\n`, tar padding to block-size=512b boundary and tar trailer (two zero blocks). Frame-aware compression is something that is already done in `autoclave_tar()`, so it can be extended withing some reasonable complexity budget.

Also, #53 may be worth investigation as it also deals with tar trailer.

Of course, different ways are also possible including...
- ditching the idea of ~64MiB mini-batches stored as tar.lz4 files
- ditching Aiflow scheduler altogether as different steps within the bucket are getting more tightly integrated
- changing data format to something more modern (and capable of handling data that never had enforced schema)

It's unclear if the described way is a ~best~ good one.

**Comment by hellais** [comment]
This has been done and is just waiting deployment: https://github.com/ooni/sysadmin/issues/394
