### ISSUE TITLE
Add blockpage fingerprints for SD

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#217]
Adds a list of blockpage fingerprints for Sudan.

#### tag: `gateprotect`
Example measurements:
https://explorer.ooni.io/measurement/20181223T053338Z_AS37211_SNSyW5GQvxWDuQ2tQpJNZKqK5IyQFfXAVgTQynYjVzUvZn2FDK?input=http:%2F%2Fwww.bglad.com

https://explorer.ooni.io/measurement/20181223T053541Z_AS37211_Vjr633mrbpd5UwOkZXid7U8QnwdDILnDu63UTFd1gE7zR4gnhN

---

#### tag: `netsweeper`
Example measurement:
https://explorer.ooni.io/measurement/20181221T173618Z_AS33788_NH383fTiPbg28uZGbH9Huk4jEPJZ00IBUNrqZWLoEpbl9sx3VQ?input=http:%2F%2Fwww.pokerstars.com

**Comment by hellais** [comment]
Thanks! Added to #289
