### ISSUE TITLE
Add blockpage fingerprints for HU

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#223]
Blockpage fingerprints for Hungary.

Example measurement:
https://explorer.ooni.org/measurement/20190905T104808Z_AS50261_Y03a7meiLbuSNLjxa55pvOAYug9r0yjsFjlmfe64MzbDuGJ2UM?input=http://www.realbeer.com/
Tag: `synology`

---

Example measurement:
https://explorer.ooni.org/measurement/20190904T091911Z_AS1955_V5wcmlVrMPVZzi9sQcgAiopUjZr8umfv8XY3zHY8rOQvbTssHU?input=http://guardster.com/

**Comment by hellais** [comment]
Thanks! Added to #289
