### ISSUE TITLE
Add blockpage fingerprint for PL

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#224]
Blockpage fingerprints for Poland.

Example measurement: https://explorer.ooni.org/measurement/20190911T110527Z_AS6830_kkm1ZGUCJI4dSrRV4xl6QwG77o7EeI2PDKbwt9SPL9BBJHUsTr?input=http://www.eurogrand.com/
Tag: `http://www.finanse.mf.gov.pl/inne-podatki/podatek-od-gier-gry-hazardowe/komunikat`

---

Example measurement: https://explorer.ooni.org/measurement/20190911T110527Z_AS6830_kkm1ZGUCJI4dSrRV4xl6QwG77o7EeI2PDKbwt9SPL9BBJHUsTr?input=http://www.eurogrand.com/
Tag: `Palo Alto Networks`

---

Example measurement: https://explorer.ooni.org/measurement/20170911T085214Z_AS5617_89klUHiQWlkkbigJ33lhjVHYHCtdrflfBxRZe5M69Bd5VtZKNY?input=http://www.gayscape.com
Tag: `Checkpoint UserCheck portal`

**Comment by hellais** [comment]
Thanks added to #289.

The one tagged Palo alto networks looks the same as the first one though.
