### ISSUE TITLE
Add blockpage fingerprints for PT

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#225]
Blockpage fingerprints for PT.

Example measurement: https://explorer.ooni.org/measurement/20190911T103335Z_AS2860_4aKH0micNlcrjnWcRknF9ghAykfMdxMkWGhXWracX2FIBY6UQb?input=http://www.roxypalace.com/
Tag: `Bloqueado por ordem judicial`

---
Example measurement: https://explorer.ooni.org/measurement/20180910T235247Z_AS3243_LpUldhcfbVGUIyfOxF6TFfLNT1wSAMwHy54LBz6owWe0cofJIK?input=http://www.luckynugget.com
Tag: `Acesso bloqueado por entidade judici&aacute;ria`

**Comment by anadahz** [comment]
A middlebox/blockpage fingerprint.
Example measurement: https://explorer.ooni.org/measurement/20190411T192031Z_AS12353_JcA0e4AwUYYzR8aSXkoOiPGSiSmG8naeMOYnOPisECTr5bqelw
Tag: `AdGuard`

**Comment by hellais** [comment]
Thanks added to #289
