### ISSUE TITLE
Implement event detector which generates RSS feed

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#229]
This is a macro-issue to track work being done on the RSS feed event detector engine.

**Comment by hellais** [comment]
xref: https://github.com/ooni/pipeline/issues/230

**Comment by hellais** [comment]
xref: https://github.com/ooni/spec/issues/144 & https://github.com/ooni/spec/issues/145

**Comment by hellais** [comment]
We currently have a deployed event engine on fastpath.ooni.io. There is a web server running which exposes some sample charts and RSS feed, which we need to do some fine-tuning for (see: https://github.com/ooni/pipeline/issues/230).

The analysis is done for tuples of `(probe_cc, input)` and `(probe_cc, probe_asn, input)`.

In https://github.com/ooni/pipeline/issues/230#issue-502578757 are documented several examples of the sorts of charts which are being generated.

Below are screenshots of how the charts look like:

![Screenshot 2019-10-07 at 15 10 18](https://user-images.githubusercontent.com/424620/66314659-a518e280-e914-11e9-88d8-3c1994edbb74.png)
![Screenshot 2019-10-07 at 15 10 14](https://user-images.githubusercontent.com/424620/66314660-a518e280-e914-11e9-94aa-eff8e975387c.png)
![Screenshot 2019-10-07 at 15 10 08](https://user-images.githubusercontent.com/424620/66314661-a518e280-e914-11e9-9dc8-3d85bc431dc8.png)

The red vertical bar on the charts indicates when the even was detected.

As mentioned above we need to look at cases in which we know there to be a censorship event change (see: https://github.com/ooni/pipeline/issues/227) and fine-tune the event detector to ensure it is able to reliably detect these incidents, see: https://github.com/ooni/pipeline/issues/230

**Comment by FedericoCeratto** [comment]
The event detector isolates time periods where a service is blocked or non blocked. The green and red bars mark the beginning and end of blocking.
![Example](https://screenshotscdn.firefoxusercontent.com/images/1fb59ff4-32aa-4643-a2de-976fa615f074.png)
The detection is based on heuristics and it's meant to run on real time data as well as on historical data. We will keep refining the detection parameters to increase accuracy over time.

**Comment by hellais** [comment]
Superseeded by: https://github.com/ooni/pipeline/issues/262
