### ISSUE TITLE
Add blockpage and middlebox fingerprints for India

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#25]
A different type of block page detected blocking piratebay:
`The Page You are Looking for has been blocked`, 
https://explorer.ooni.torproject.org/measurement/7AEt2OwqdZUzFMzyZd3bFwnCwXp7FqYCezpaoBWdkBIfxtLtX84mXBZnlPLaTUqI?input=http:%2F%2Fthepiratebay.se

This depends on ooni/backend#688 .

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20170915T154832Z_AS55824_qEg9opZCyJqfZJ5qFHWMR390Y1uA6eHw7j6Fx1qtU5EPE4Jnp2?input=http:%2F%2Fwww.http-tunnel.com

https://explorer.ooni.io/measurement/20170331T050949Z_AS55824_HYIy5Ddu5UgfGq8UYBJ8aCkuz6EYAQUivivIYXDMCt6Dr6CCPU?input=http:%2F%2Fwww.babylon-x.com

tags: `Cisco-WSA/10.5.1-296`, `Cisco-WSA/10.1.0-204`

**Comment by anadahz** [comment]
Example measurement:
https://explorer.ooni.io/measurement/20180723T000524Z_AS135201_lOpTIwn8aK4gWsbfmV9v3hlTy3ZKVYHRIA8dNBAafTxmFa6hVP?input=http:%2F%2Fwww.xbox.com

tag:`GoAhead-Webs`

**Comment by hellais** [comment]
@anadahz I cannot find the measurement you link to in: https://github.com/ooni/pipeline/issues/25#issue-154919607. @FedericoCeratto do you know what may be causing this?

**Comment by hellais** [comment]
Added these to: https://github.com/ooni/pipeline/pull/289
