### ISSUE TITLE
Add Russian block page detection fingerprint

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#26]
Ref: https://explorer.ooni.torproject.org/measurement/fDYllw7vRf71n2l4g2V2ahIlPxmd6nrpsjWemcJDWX1UDN0AT5Z5uBh4HhAdFdGB?input=http:%2F%2Fthepiratebay.se%2F

This task depends on ooni/backend#688 .

**Comment by hellais** [comment]
Added to: https://github.com/ooni/pipeline/pull/289
