### ISSUE TITLE
Discuss and do some exploration for data analysis needed by research reports

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#263]
This can also involve looking at:
https://github.com/ooni/pipeline/issues/61
https://github.com/ooni/pipeline/issues/45
https://github.com/ooni/pipeline/issues/46

and is a direct requirement to completing:
https://github.com/ooni/pipeline/issues/260
& https://github.com/ooni/pipeline/issues/261

**Comment by FedericoCeratto** [comment]
I've spent few hours experimenting with:
1) Importing categories from input JSON files into the database
1.1) ...same, plus extracting the historical changes to the files using git history
2) modify the event detector webapp to add an "olap-like" query to slice data cubes

**Comment by hellais** [comment]
We have created the citizenlab table which includes the category codes necessary for the creation of research reports.

This can be considered done in the previous cycle.
