### ISSUE TITLE
Move ooni-data-private into ooni-data

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#273]
What needs to happen is:

* [x] Update the pipeline to publish data in ooni-data instead of ooni-data-private (see: https://github.com/ooni/sysadmin/pull/409)
* [x] Wait for the pipeline to tick one day and verify that data is getting written properly
* [x] Copy all the data from ooni-data-private into ooni-data
* [x] Delete the original data from ooni-data-private

This is related to openly published even the cans that are currently stored in ooni-data-private.

These are the raw un-normalized/un-sanitized data. The only relevant sanitisation process is that of redacting certain bridge IP addresses which were tested during the period which goes from 2014-10-03 00:00:10 to 2015-05-28 05:38:10.

By moving them into the ooni-data bucket we will be consolidating all our s3 resources inside of the same account making it easier for us to manage the publication of data.

**Comment by hellais** [comment]
@nullhypothesis is looking to check if in fact it is OK to public the very old bridge IP addresses and if so we can move forward with the migration of the data.

We would like to complete this task within the week or two.

**Comment by NullHypothesis** [comment]
The only bridges that were still online when I checked the list were Linus's former obfs3 default bridges. We emailed Linus and he's ok with this data being published. I would say let's move forward with this!

**Comment by hellais** [comment]
Excellent, thanks for following up. I will add a checklist of what we need to do in the issue description.

**Comment by hellais** [comment]
I have started this today at around 16:00 Rome time:

```
/usr/bin/python3 /usr/bin/aws s3 sync --request-payer requester s3://ooni-data-private s3://ooni-data
```

After 2:30h, we are at:
```
copy: s3://ooni-data-private/archives-raw/yaml/2017-01-02.tar.gz to s3://ooni-data/archives-raw/yaml/2017-01-02.tar.gz
```

It will take a while...

**Comment by hellais** [comment]
... and 3 days later:

```
Completed 8.6 TiB/~8.6 TiB (37.1 MiB/s) with ~188 file(s) remaining (calculating...)
copy: s3://ooni-data-private/canned/2019-05-09/web_connectivity.11.tar.lz4 to s3://ooni-data/canned/2019-05-09/web_connectivity.11.tar.lz4
copy: s3://ooni-data-private/canned/2019-05-09/web_connectivity.10.tar.lz4 to s3://ooni-data/canned/2019-
```

Getting there...

**Comment by hellais** [comment]
This was actually already tracked in: https://github.com/ooni/sysadmin/issues/395.

**Comment by hellais** [comment]
The copy is finished. As a sanity check before dropping everything I am doing:

```
aws s3 ls --request-payer requester --recursive s3://ooni-data-private > data-private-ls.txt
aws s3 ls --request-payer requester --recursive s3://ooni-data > data-ls.txt
```

and checking the two outputs for consistency as an extra safety check.

**Comment by hellais** [comment]
Here is the result of the sanity check: https://gist.github.com/hellais/9fccb101d415839ad177957083fd1f6c.

As we can see only files from the most recent buckets are the difference between the two. I am going to proceed with deleting the data at the source.

**Comment by hellais** [comment]
The files in ooni-data-private have all been deleted. The ec2 host used for the sync and deletion has been terminated.

All the OONI data is now public!
