### ISSUE TITLE
Run a pipeline workflow for the unprocessed GB reports

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#28]
A similar [workflow](https://github.com/TheTorProject/ooni-pipeline#daily-workflow) should be run on the pipeline to process the older (before 2016-06-07) and archived ooni-probe reports for GB.

**Comment by darkk** [comment]
I believe, that was done, if those reports were available on datacollector. As far as I remember, GB reports were available.

But, please, correct me if I'm wrong (and that's still relevant) and re-open the ticket.
