### ISSUE TITLE
Redesign the data processing pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#32]
We should write a design document for how the next iteration of the data processing pipeline.

This design document should feature:
- How data is ingested into the pipeline (how is data published to it, how does it fetch data from third parties)
- What are the various data processing stages that it should go through
- How it is analysed and post processed for being consumed by the explorer
- What are the output data products of it
- What technological choices should be made for the various software components of it

On the last point I have looked a bit into airflow (https://github.com/apache/incubator-airflow). I quite like it's model and would be interested in considering it as a workflow engine to replace luigi.

What I like very much about it are:
- It has it's own scheduler and doesn't require us to depend on cron for triggering the period tasks
- It supports using celery based message queues for scheduling tasks to be run (http://pythonhosted.org/airflow/concepts.html#queues)
- The operators support templating via jinja2 and there is a `BashOperator` that is quite flexible

cc @willscott

**Comment by willscott** [comment]
Airflow looks like it can help organize a bunch of the complexity in the current structure! The design points to make sure we can do cleanly should include:
- How does a submission get into the pipeline? If we have a web hook for submission, can that go in a message queue? what does that ingestion look like?
- If we want regular incremental updates, how well does airflow do? we'll eventually want at least hourly updates of some products.

**Comment by ghost** [comment]
@hellais @willscott: to expand on this a little bit, I can definitely see how Airflow's trigger / hook / sensor routines could be used to improve the overall flexibility of `ooni-pipeline`. 

Pros: 
- Apache Airflow provides its own schedule which opens up the possibility of autonomously triggering time-based jobs (e.g. back-up, archival, and reporting);
- Apache Airflow provides sensors, hooks, and triggers which could be used to build an event-driven pipeline;
- Apache Airflow would open up the possibility of submitting `ooni-probe` test results directly from collectors given the presence of sensors / hooks / triggers;
- The technical complexity associated with developing new operators seems to be minimal; and
- The user community is pretty active:
  - https://groups.google.com/forum/#!forum/airbnb_airflow
  - http://mail-archives.apache.org/mod_mbox/incubator-airflow-dev/201606.mbox/browse

I'd like to propose the following points on top of what's already been listed:
- How is the intermediate state of test data within each pipeline phase going to be maintained?
- What intermediate format should test data be in between each pipeline phase?
- Should the pipeline be distributed, or should it be consolidated to one node?
- What were the bottlenecks associated with the previous iteration?
- Where should data be stored in relation to the data processing pipeline?
- What does the pipeline need to do? Should the responsibility of the pipeline be limited to data ingestion and normalization, or should it also perform analytics and anomaly detection?

Additional information:
- Airflow @ Agari: https://www.agari.com/airflow-agari/

**Comment by darkk** [comment]
Birdeye view of the dataflow (to be stored in ooni-pipeline/docs/ later).

Infra
=====

Datastore is currently filesystem-based, but all code is written in streaming way to make migration to objectstore easier.

Airflow is "smart cron" manager, airflow is deployed with docker. Exact recipe is based on [puckel/docker-airflow](https://github.com/puckel/docker-airflow/) and some crutches overlayed on top of that image.

Data processing happens in separate container (*ooni/shovel*) to avoid bringing unstable dependencies to airflow container as mixing unstable software is scary.


Data flow
=========

There are three major "daily" steps: 1. *canning*, 2. *autoclaving*, 3. *centrifugation*.

**Canning** converts reports-raw to tar.lz4 files in following way:
`canning-1.py | tar c 2000-13-42/foo.yaml 2000-13-42/bar.json | canning-2.py | lz4 -5 | canning-3.py`
canning-1: group reports by `test_name`, slice tham into ~64 Mbytes groups of uncompressed data, send them to `tar`
canning-2: read tar file, verify sizes of reports, calculate sha1 and crc32 of each report, calculate size of tar file, pipe it to `lz4`
canning-3: read lz4 from the pipe, calculate it's size, sha1 and crc32, dump lz4 & all the checksums to disk

All the sizes are recorded to be checked to avoid various sort of unexpected file truncations.

**Autoclaving** replaces normalization and sanitization, it converts tar.lz4 files in 1:1 way.
lz4 compression is a bit tricky at this stage: lz4 frames are independent, report offsets within the block are recorded in the separate index file, so the resulting file is both streamable (with ability to skip tar records without decoding), seekable (single lz4 frame is read to get a single report — that's either ~56kb of ~227kb of compressed data) and readable with ordinary `tar -I lz4 --extract` for whoever wanting to parse sanitized measurements.

Indexes for the reports are stored as well, they include block offsets, sizes, and offsets within block required to seek() to exact measurement and to read the file in streaming way without parsing tarfile stream.

**Centrifugation** is done to enrich the data.
It reads data sanitized by autoclaving, extract the aggregatable essence and stores metadata into postgresql db for further processing.
More on this step later.

Highlights
==========

*Daily?* — I say *daily* as it daily bucket gives better compression ratio and more "sane" data chunks for HDD-based storage for later re-processing. Autoclaving and centrifugation may be done on incoming raw data more often, but end-of-the day wrap-up sounds reasonable.

*tar?* — Each tiny report costs several IO operations. That produces measurable slowdown if the data is HDD-stored, so we need some "streaming" way to read and write reports.

*${test_name}.42.tar.lz4* — re-centrifugation is likely triggered by some new code that can extract some new value from existing data and it usually depends on test type.
