### ISSUE TITLE
Define data formats for interoperability of data from different platforms

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#33]
We should have a guideline of how data should be structured and formatted in order to be injested into the ooni-pipeline.

At the bare minimum we should include:
- What is the data format of the files to be processed (http://jsonlines.org/?)
- What are some semantics for the minimum set of elements to be present inside of the documents

I think we should be covering the following types of measurement/data:
- Data that is pertaining to measurements conducted from a centralised vantage point and the data is not pertinent to where it was run from (i.e. satellite)
- Data that is pertaining to measurements conducted from many vantage points and the measurement is pertinent to from where the measurement is run (i.e. ooni-probe, iclab)
- Other complementary data that is not necessarily network measurements, but is useful to better understanding the context of a given country (ex. DFA, CIA factbook, etc.)

cc @willscott

**Comment by willscott** [comment]
Agreed. What's the right place for this to live? It would be great to have a wiki that the different efforts in this space can contribute the keys they're using, along with the specification and examples. 
- A page on ooni-web could work, though it won't be as easy for others to update
- Documentation of the basic formats seems to fit most naturally in ooni-spec
- The complementary data seems to most naturally fall in the openobservatory.org scope

**Comment by hellais** [comment]
This is to some extent done. @bassosimone maybe there is some knowledge to be moved elsewhere.
