### ISSUE TITLE
Allow ooni-pipeline to be run against a set of ooni-probe reports stored locally, or in a public S3 bucket

### ISSUE THREAD

**Issue by ghost** [ooni/pipeline#36]
Since `ooni-pipeline` is responsible for normalising `ooni-probe` reports which may exist in a variety of formats, it's important to be able to validate the integrity of the pipeline, as well as its outputs. In doing so, we can effectively reduce the costs associated with running the pipeline for development purposes.

In order to accomplish this, we would have to ensure that:
- An instance of `ooni-pipeline` can be deployed to TravisCI; and that
- The pipeline can be run by users who do not have privileged access to S3.

However, the entirety of the pipeline can currently only be run by users who have privileged access to S3. Effectively, this ticket would allow `ooni-pipeline` to be run in an unprivileged CI environment for the purpose of performing integration tests against the pipeline, in addition to lowering the barriers to contributing to pipeline development.

See: https://github.com/TylerJFisher/ooni-lyzer/issues/12

**Comment by darkk** [comment]
That kinda happened as a part of #144 and other activities. It's possible to run *.json -> PosgreSQL step locally without privileged access to S3 (but "data normalization step" still needs privileged access to private data).
So I assume that the issue can be marked as a closed one.
