### ISSUE TITLE
Make bucket_name=${execution_date} again!

### ISSUE THREAD

**Issue by darkk** [ooni/pipeline#55]
Seems, `generate-streams-import-in-db.sh` introduced a regression:

Before: ${bucket_name} reflects _beginning_ of the day when the reports came
After: ${bucket_name} reflects beginning of the _next_ day after the reports came

![delta-canned.png](https://cloud.githubusercontent.com/assets/21046/24678151/1dd03a02-1992-11e7-9f2d-4ae11b053451.png)

I consider _fixing_ that regression, so ${bucket_name} will reflect airflow's `execution_date` that is the beginning of the interval.

Side effects are:
- 24h processing delay in airflow while luigi controls the pipeline as `2017-01-01` bucket is generated at ~ `2017-01-01 00:30 UTC` and is processed by airflow at `2017-01-02 00:00 UTC`
- 24h processing delay when switchover from luigi to airflow takes place

**Comment by hellais** [comment]
I don't have a problem with any of these side effects and I think it's good to use whatever you would expect the behaviour to be.

**Comment by darkk** [comment]
[FTR](https://github.com/ooni/sysadmin/blob/b9e8e91/ansible/roles/airflow/files/airflow-dags/shovel_jump.sh), that's how it works now.

The ticket was here mostly to document that `${bucket_date}` could mean both edges of the corresponding date in different historical periods.
