### ISSUE TITLE
Ugly escaping of AS names

### ISSUE THREAD

**Issue by darkk** [ooni/pipeline#60]
On one hand [AS1919](https://explorer.ooni.torproject.org/measurement/20170426T225124Z_AS1916_9iIkKBUGlL25hG8jIdekfDdYzwS6T3IJncAOwtsofMF0X13cyV) is shown as ugly `Associa\195\167\195\163o...` instead of `Associação...`
On the other hand it protects against weird unicode stuff coming from external source.

@hellais what do you think, is it a bug or a feature?

**Comment by hellais** [comment]
We don't resolve AS names anymore in explorer, closing.
