### ISSUE TITLE
Add an issue template for reporting false positive/negatives

### ISSUE THREAD

**Issue by anadahz** [ooni/pipeline#63]
A template for issues related to reporting false positive/negatives should be made for the [ooni-pipeline](https://github.com/TheTorProject/ooni-pipeline) repository.

We can then move issues around to another repository if the report is software specific related (eg. ooniprobe, ooniprobe-android, ooniprobe-ios, lepidopter)

**Comment by hellais** [comment]
This is superseeded by https://github.com/ooni/explorer/issues/213
