### ISSUE TITLE
Explorer: Missing blocked websites on 'blocked websites' section on country dashboard

### ISSUE THREAD

**Issue by tafiti** [ooni/pipeline#66]
See this for example: https://explorer.ooni.torproject.org/measurement/20170118T195954Z_AS24757_uOGxu3ZK42YqwvMKTsfbIjiVAiXk6uQpyvmlM9fK4ZnlKLloFt?input=http:%2F%2Fecadforum.com%2F

There are over 40 blocked websites in ET on our test list but they are not listed. 

Is it by accident or design?

**Comment by anadahz** [comment]
[OONI explorer](https://explorer.ooni.torproject.org) (currently) is showing up blocked websites when the following criteria met:
- An identified fingerprint has been "registered" to the pipeline [block page body fingerprints](https://github.com/TheTorProject/ooni-pipeline/blob/master/pipeline/batch/sql_tasks.py#L11) or the [blockpage header fingerprints](https://github.com/TheTorProject/ooni-pipeline/blob/master/pipeline/batch/sql_tasks.py#L27)
- A block page is being detect; a landing page (usually in HTML) or a redirect to a block page, eg: https://explorer.ooni.torproject.org/measurement/bE35lS71t9vU2Swm2gxSdNPl9DWcaZpRizWrxyGEV7rh8srASwPnuwQIkdVoph0b?input=http:%2F%2Fanonym.to%2F
