### ISSUE TITLE
Add blockpage for referendum sites in Catalonia

### ISSUE THREAD

**Issue by botherder** [ooni/pipeline#82]
As you know, sites and mirrors of sites dealing with referendum in Catalonia are being seized or otherwise DNS blocked.

Here is the content of the blockpage, which seems pretty standard:

```<!doctype html><html><head> <meta charset="utf-8"> <meta name="keywords" content=""> <meta name="description" content=""> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <link rel="shortcut icon" type="image/png" href="/estaticos_nodisponible/favicon.jpg"> <link rel="stylesheet" type="text/css" href="/estaticos_nodisponible/css/bootstrap.min.css"><link rel="stylesheet" type="text/css" href="/estaticos_nodisponible/style.css"><link rel="stylesheet" type="text/css" href="/estaticos_nodisponible/css/font-awesome.min.css"> <script src="/estaticos_nodisponible/js/jquery-2.1.0.min.js"></script><script src="/estaticos_nodisponible/js/bootstrap.min.js"></script><script src="/estaticos_nodisponible/js/blocs.min.js"></script><script src="/estaticos_nodisponible/js/jquery.touchSwipe.min.js" defer></script><script src="/estaticos_nodisponible/js/lazysizes.min.js" defer></script> <title>Dominio-No-Disponible</title> <!-- Google Analytics --> <!-- Google Analytics END --> </head><body><!-- Main container --><div class="page-container"> <!-- bloc-0 --><div class="bloc bgc-white full-width-bloc" id="bloc-0"><div class="container"><div class="row"><div class="col-sm-12"><div id="carousel-1" class="carousel no-shadows slide" data-ride="carousel"><ol class="carousel-indicators hide-indicators"><li data-target="#carousel-1" data-slide-to="0" class="active"></li></ol><div class="carousel-inner"><div class="item active"><img src="/estaticos_nodisponible/img/Front.png" /><div class="carousel-caption"></div></div></div><a class="left carousel-control" href="#carousel-1" role="button" data-slide="prev"><span class="fa fa-chevron-left"></span><span class="sr-only">Previous</span></a><a class="right carousel-control" href="#carousel-1" role="button" data-slide="next"><span class="fa fa-chevron-right"></span><span class="sr-only">Next</span></a></div></div></div></div></div><!-- bloc-0 END --><!-- ScrollToTop Button --><a class="bloc-button btn btn-d scrollToTop" onclick="scrollToTarget('1')"><span class="fa fa-chevron-up"></span></a><!-- ScrollToTop Button END--></div><!-- Main container END --> </body></html>```

Here is one example measurement:
https://explorer.ooni.torproject.org/measurement/20170925T151843Z_AS12338_JMQ1OWOJQQ4WsPmSNRi6HsR5w5tMSX2IgNeXhLN5wUCB7051jX?input=http:%2F%2Fwww.ref1oct.eu%2F

Bear in mind that .cat domains are getting seized instead (and reconfigured to be served on Akamai), but the block page seems the same.

**Comment by hellais** [comment]
Thanks for this!

**Comment by hellais** [comment]
Added to: https://github.com/ooni/pipeline/pull/289
