### ISSUE TITLE
Move data proxy from HKG to AMS

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#86]
As mentioned in: https://github.com/TheTorProject/ooni-pipeline/pull/62, we should consider if it makes sense to (taken from @darkk comments):

* [ ] Move data proxy from HKG to AMS
* [ ] Split large reports -- no good reason to do that yet
* [ ] verify that 90kb can be really fetched using keep-alive within 1 RTT
  * for i in seq 35; do curl -sS -w 'time_total: %{time_total}\n' -o /dev/null -H 'Range: bytes=0-1550000' http://127.0.0.1/64M; sleep 2 ; done
  * bytes=0-1600000 is bad & net.ipv4.tcp_slow_start_after_idle=0
  * plain ip route add … initcwnd 1200 does not reduce 1st req latency (but that's fixable), sort of "Persist cwnd" at https://www.chromium.org/spdy/spdy-best-practices

**Comment by darkk** [comment]
That is probably not relevant and should be closed as `dataproxy` idea is currently dead.
