### ISSUE TITLE
Investigate data mismatches

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#88]
Mentioned by @darkk in https://github.com/TheTorProject/ooni-pipeline/pull/62:

* [ ] no sanitiesed data: ooni/private/reports-raw/2016-05-17/20160516T070552Z-GB-AS5607-http_requests-no_report_id-0.1.0-probe.yaml
* [ ] outliers -- measurements with 13mb of COMPRESSED data, 2014-11-22 with ~1M measurements
* [ ] 2017-02-14 bucket has no "benign mismatches" log stored, consider recomputing
* [ ] partial bucket processing and re-processing to be tolerant to issues like #65

**Comment by darkk** [comment]
Sanitized / benign mismatches story is stopped as "good enough".

Partial bucket processing is done.

Few more outliers those may be useful for testing are:

- 2014-11-23 that also has high number (~1M) of measurements
- 2016-04-01 that has high number of distinct report files
- 2018-06-01 that has `badblob`
- [precise bucket forgotten] LZ4 frame with no `datum`, so it's not accounted in `measurements` table
