### ISSUE TITLE
Improve pipeline infrastructure

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#89]
Mentioned by @darkk in https://github.com/TheTorProject/ooni-pipeline/pull/62:

* [x] set up AMS replica of HGK metadb
* [x] ntp and poweroff safety, TheTorProject/ooni-sysadmin#101
* [x] consider backups / replicas of metadata DBs

**Comment by darkk** [comment]
All of that is done some time ago and the issue should be closed.
