### ISSUE TITLE
Massage data in new pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#90]
Mentioned by @darkk in https://github.com/TheTorProject/ooni-pipeline/pull/62:

* [ ] scripts to manage redundant copies of data in Amazon S3
* [ ] check mismatches between sanitized and autoclaved
* [ ] re-run whole pipeline as shovel:0.0.6 had a bug possibly producing duplicates at features table on two successful executions of centrifugation.py with same arguments (no idempotence here)
* [ ] check if any reports/measurements were lost due to JOIN instead of LEFT JOIN on metadata tables

**Comment by darkk** [comment]
> mismatches between sanitized and autoclaved

There are some mismatches still left, but they're minimal and it was considered (long time ago) that those are irrelevant.

Everything else was done as a one-shot (natural/left joins have actually caught an interesting case of an empty report: 220417f8aa57360fcb94eae2e1d6caf7d48a36b2). Maybe there should be some monitoring code comparing the number of reports & measurements submitted to collector with the number ingested by the pipeline, but that's unclear to me.

I think this issue may be closed now.
