### ISSUE TITLE
Shutdown legacy luigi pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#94]
Finally deprecate the legacy luigi pipeline and rely only on the airflow based one.

Mentioned by @darkk in https://github.com/TheTorProject/ooni-pipeline/pull/62

**Comment by darkk** [comment]
That's done since https://github.com/ooni/sysadmin/commit/b9e8e914d56f1d69e6116ee76ea08208794e444d and https://github.com/ooni/sysadmin/pull/233
So I'm closing the ticket.
